### PR TITLE
button styles

### PR DESCRIPTION
**Pull request by EgleJuske**
buttons styles with hover transitions for:
- hero buttons
- form button
- main gradient buttons (regular and round)

### CODE REVIEW

**Review by JurateJ — CHANGES_REQUESTED** [review]
btn jei bus naudojamas su button matysis borderis

**Comment by EgleJuske** [comment]
aš uždėjus `border: none`, tai neturėtų matytis border. Kai dariau testavausi ant tag'ų `<div> <a> <button>`

**Review by Jjurgita — DISMISSED** [review]
No worries, it's a really great start 👍  Both hero buttons are visible, we only need to change the background color for that.

**Review by JurateJ — DISMISSED** [review]
I like it!

**Review by Jjurgita — DISMISSED** [review]

**Review by Jjurgita — APPROVED** [review]

**Review by InetaVei — APPROVED** [review]

**Review by JurateJ — APPROVED** [review]

**Pull request merged**
