### PR TITLE
add decoration to titles #70

### PR DESCRIPTION
**Pull request by EgleJuske**
- added decoration to titles
- made changes in margins between sections

### CODE REVIEW

**Comment by Jjurgita** [comment]
Great job! 
Still missing decoration in the footer section, but maybe we can add it later. What do you think? :)

**Comment by EgleJuske** [comment]
> Great job!
> Still missing decoration in the footer section, but maybe we can add it later. What do you think? :)

Missed those 😵 i will add the title deco for footer in the wider background issue.

**Comment by Jjurgita** [comment]
oh, I already take that issue, but you can do it if you want :) I better go with the slider then

**Review by JurateJ — APPROVED** [review]
Nice!

**Review by Jjurgita — APPROVED** [review]

**Review by Ramazinas — APPROVED** [review]

**Pull request merged**
